### PR TITLE
Merge libovsdb changes into master branch of our fork

### PR DESCRIPTION
**Pull request by shaleman**
Godeps does not seem to handle importing from branches very well. 
This fixes some of the import paths and merges all our changes into master branch of contiv/libovsdb so that we can correctly godep import contiv/libovsdb into netplugin

### CODE REVIEW

**Comment by shaleman** [comment]
I'm declaring from now on contiv is the primary maintainer of libovsdb :)

**Comment by erikh** [comment]
if we're forking it, we should probably declare so in the docs ("a fork of socketplane/libovsdb") and probably inform @davetucker and co and let them know why so they have the opportunity to merge our changes.

**Comment by erikh** [comment]
another thought: we should probably distinguish ourselves in the docs as well,  so it's apparent to end-users what has changed.

**Comment by unclejack** [comment]
I'll merge this for now to enable us to fix godeps across all projects. Once we're done with that, we can upstream all of our changes to socketplane/libovsdb. This means we won't fork libovsdb.

**Pull request merged**
